### ISSUE TITLE
CSV Not Created

### ISSUE THREAD

**Issue by jamiewharton** [H4zh4n/MyCounter#1]
Great app, very keen to use it, but this hinges upon me being able to create a CSV from it.

At the moment this feature doesn't work for me. Using a Samsung Galaxy XCover 5 I go to the Create CSV option and something flashes up on the screen for a fraction of a second and then nothing happens.

When I go to the directory in /data... then there is nothing there, it creates a CSV and a timestamped folder within it but it is empty. I have enabled View hidden files in Windows but still can't see anything in there.

I am able to create backup files ok and use them to restore counter lists without issue, so the app can write files to the phone.

Is there anything you can suggest?

**Comment by H4zh4n** [comment]
Thank you for reporting it 🌸
I did notice it a-few weeks ago and fixed it, but didn't have enough free time to push an update, apologies for that.
hopefully I'll push one soon enough and please let me know if it gets fixed or not 🌸

**Comment by H4zh4n** [comment]
@jamiewharton 
version 1.0.3 just got released, may take a couple hours until it shows up for everyone.
I would be very grateful if you could update it and report back whether it works or not now.

Will keep the issue up for awhile until you report back to me. 🌸
